# Site settings
title: Coding the Thosmos
description: "Programming the universe one byte at a time"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://code.thosmos.com" # the base hostname & protocol for your site
twitter_username: thosmos
github_username:  thos37

# Build settings
markdown: kramdown
